apiVersion: v1
kind: Service
metadata:
  name: spark-master
  labels:
    app: spark
    role: master
spec:
  type: ClusterIP
  selector:
    app: spark
    role: master
  ports:
    - name: spark
      port: 7077
      targetPort: 7077
      protocol: TCP
    - name: webui
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: notebook
      port: 8888
      targetPort: 8888
      protocol: TCP
    - name: torch
      port: 29500
      targetPort: 29500
      protocol: TCP