apiVersion: v1
kind: Service
metadata:
  name: spark-worker
spec:
  clusterIP: None  # Headless
  selector:
    app: spark
    role: worker
  ports:
    - name: ddp
      port: 29500
    - name: webui
      port: 8081
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-worker
spec:
  serviceName: spark-worker
  replicas: 7
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:     
      containers:
        - name: spark-worker
          image: jfriasl-spark-base
          imagePullPolicy: Never  
          command: ["/opt/spark/bin/spark-class"]
          args: ["org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
          ports:
            - containerPort: 8081
            - containerPort: 29500
          volumeMounts:
            - mountPath: /mnt/volume
              name: shared-volume
          env:
            - name: TORCH_DISTRIBUTED_PORT_RANGE
              value: "29500-29519"
      volumes:
        - name: shared-volume
          hostPath:
            path: /mnt/volume
